import { ROLES } from '../utils/constants';

export const roleRoutes = {
  dashboard: [ROLES.SUPER_ADMIN, ROLES.ADMIN, ROLES.MANAGER, ROLES.RECEPTION, ROLES.RESIDENT],
  apartments: [ROLES.SUPER_ADMIN],
  expenses: [ROLES.ADMIN, ROLES.MANAGER, ROLES.RESIDENT],
  notices: [ROLES.SUPER_ADMIN, ROLES.ADMIN, ROLES.MANAGER, ROLES.RECEPTION, ROLES.RESIDENT],
  complaints: [ROLES.SUPER_ADMIN, ROLES.ADMIN, ROLES.MANAGER, ROLES.RECEPTION, ROLES.RESIDENT],
  directory: [ROLES.SUPER_ADMIN, ROLES.ADMIN, ROLES.MANAGER, ROLES.RECEPTION, ROLES.RESIDENT],
  visitors: [ROLES.ADMIN, ROLES.MANAGER, ROLES.RECEPTION],
};
